INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('The Big Bang', 'The event that led to the formation of the universe', '13.8 billion years ago', 100);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('Formation of Earth', 'The formation of our planet', '4.6 billion years ago', 100);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('Origin of Life', 'The emergence of the first living organisms', '3.8 billion years ago', 100);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('Development of Agriculture', 'Transition from hunter-gatherer societies to settled farming communities', '10,000 BCE', 90);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('Invention of Writing', 'The development of written language', '3,200 BCE', 95);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('Building of the Great Pyramids', 'Construction of the pyramids of Giza in Egypt', '2,560 BCE', 90);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('Rise of Ancient Greece', 'The birth of Greek civilization and democracy', '800 BCE', 95);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('Fall of the Roman Empire', 'The decline and eventual collapse of the Roman Empire', '476 CE', 100);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('The Renaissance', 'Revival of art, science, and literature in Europe', '14th-17th century', 95);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('American Revolution', 'The rebellion of the American colonies against British rule', '1775-1783', 95);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('Industrial Revolution', 'Transformation of manufacturing and economy through mechanization', '18th-19th century', 100);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('World War I', 'Global conflict involving major world powers', '1914-1918', 100);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('Russian Revolution', 'Overthrow of the Russian monarchy and establishment of the Soviet Union', '1917', 95);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('World War II', 'Deadliest conflict in human history involving many countries', '1939-1945', 100);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('End of Apartheid', 'The dismantling of racial segregation in South Africa', '1994', 90);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('The Moon Landing', 'First manned mission to land on the Moon', '1969', 95);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('The Internet Revolution', 'The development and widespread use of the internet', 'late 20th century', 100);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('Fall of the Berlin Wall', 'Symbolic end of the Cold War and the division of Germany', '1989', 95);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('Invention of the World Wide Web', 'Tim Berners-Lee creates the web', '1989', 90);
INSERT INTO events (event_name, description, timestamp, relevance) VALUES ('COVID-19 Pandemic', 'Global pandemic caused by the novel coronavirus', '2019-present', 100);